name: Terraform

on:
    pull_request:
      branches:
        - main
      paths:
        - 'terraform-modules/**'    # Only trigger when files in the terraform directory -
        - 'dev/**'                  # and dev directory -
        - 'prod/**'                 # and prod directory are changed
        - '!README.md'      # Ignore changes to README.md
  
    push:
      branches:
        - main
      paths:
        - 'terraform-modules/**'    # Only trigger when files in the terraform directory -
        - 'dev/**'                  # and dev directory -
        - 'prod/**'                 # and prod directory are changed
        - '!README.md'      # Ignore changes to README.md

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials configured."
      
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
  
      - name: Decode SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/asg-deploy.pem
          chmod 400 ~/.ssh/asg-deploy.pem
          echo "SSH key created at ~/.ssh/asg-deploy.pem"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-modules/ec2-instances
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform-modules/ec2-instances

      - name: Terraform Plan
        run: terraform plan -var="instance_type=${{ secrets.INSTANCE_TYPE }}" -var="ami_id=${{ secrets.AMI_ID }}" -var="region=${{ secrets.AWS_REGION }}" -var="ssh_ip=${{ secrets.SSH_IP }}" -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="ssh_key_path=~/.ssh/asg-deploy.pem" -var="key_name=${{ secrets.AWS_KEY_NAME }}"
        working-directory: terraform-modules/ec2-instances
        
      - name: Terraform Apply # run only on merged PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="instance_type=${{ secrets.INSTANCE_TYPE }}" -var="ami_id=${{ secrets.AMI_ID }}" -var="region=${{ secrets.AWS_REGION }}" -var="ssh_ip=${{ secrets.SSH_IP }}" -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="ssh_key_path=~/.ssh/asg-deploy.pem" -var="key_name=${{ secrets.AWS_KEY_NAME }}"
        working-directory: terraform-modules/ec2-instances