name: Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Create terraform.tfvars file
        run: |
          mkdir -p terraform  # Create the directory if it doesn't exist
          echo "instance_type = \"${{ secrets.INSTANCE_TYPE }}\"" >> terraform/terraform.tfvars
          echo "ami = \"${{ secrets.AMI_ID }}\"" >> terraform/terraform.tfvars
          echo "region = \"${{ secrets.AWS_REGION }}\"" >> terraform/terraform.tfvars

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Path for the .tfvars

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: terraform  # Path for the .tfvars